### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ofalah** [xiaobin1231/Fall-Detection-By-YOLOV3-and-LiteFlowNet#5]
hi i get this error can you help me plase

Traceback (most recent call last):
  File "detect.py", line 8, in <module>
    from LiteFlowNet.run import Network, batch_estimate
  File "/home/fal/Downloads/Fall-Detection-By-YOLOV3-and-LiteFlowNet-master/LiteFlowNet/run.py", line 21, in <module>
    assert(int(str('').join(torch.__version__.split('.')[0:3])) >= 41) # requires at least pytorch version 0.4.1
ValueError: invalid literal for int() with base 10: '170+cu110'

**Comment by ofalah** [comment]
I'm using GPU RTX 3090 24gb

**Comment by mahesh2496** [comment]
me to facing same issue

**Comment by af-doom** [comment]
> hi i get this error can you help me plase
> 
> Traceback (most recent call last): File "detect.py", line 8, in from LiteFlowNet.run import Network, batch_estimate File "/home/fal/Downloads/Fall-Detection-By-YOLOV3-and-LiteFlowNet-master/LiteFlowNet/run.py", line 21, in assert(int(str('').join(torch.**version**.split('.')[0:3])) >= 41) # requires at least pytorch version 0.4.1 ValueError: invalid literal for int() with base 10: '170+cu110'

I also

**Comment by nguyenduylinhqbu** [comment]
Me too. Please help!
